### ISSUE TITLE
Add Bendpoints to Links

### ISSUE THREAD

**Issue by altran-fabian** [MrBlenny/react-flow-chart#117]
Ok i am really enjoying to play with the flowchart. now i get some nice graph's rendered from an mermaid like input: 
```
Screen_01_WelcomeLastUser[WelcomeLastUser]-->d0?{Nutzerwechsel?}
d0? -->|no|UserHomeScreen
d0? -->|yes|IAA_Screen_02_ChangeUser

Screen_02_ChangeUser--> d1?{New User?}
d1? -->|no|IAA_Screen_01_WelcomeLastUser
d1? -->|yes|IAA_Screen_03_01_WelcomeToWeConnect
```
it would be nice to add some bendpoints to the generated links. So all connections going backwards can be aligned. otherwise they are just overlapping the nodes. 

do you have any idea how i could achieve this? is a plugin or a feature like this is planed?

![image](https://user-images.githubusercontent.com/59995045/78546789-50d8b780-77fe-11ea-88d6-3a67f408f3b9.png)

**Comment by altran-fabian** [comment]
fyi: 
i tried using the `config={{ smartRouting: true }}` option but it breaks the application. it routes the connections but freezes and leads my machine to burn ... maybe there is some bug in the smartRouting?

**Comment by MrBlenny** [comment]
I'm not sure what is causing the smartRouting to break. I was not planning on adding an display related config to the links. Doing so would probably be out of the scope of this project as the primary use is for creating programmatic flows rather than just displaying. If you can replicate the smartRouting issue please create raise it.
