### ISSUE TITLE
Any idea to implement Arrow on Links.

### ISSUE THREAD

**Issue by Naveenraj006** [MrBlenny/react-flow-chart#73]
I want to implement an Arrow at the edge of links. Can you give me an idea or hack to implement this?

**Comment by ColemanCollins** [comment]
You can make a custom Link component that uses an SVG `<marker>` to drop an arrowhead on the end of a link. The challenge with this is that the way the current link path drawing/curve generation works, it actually flips the start/end points depending on the spatial relationship of the nodes rather than their directed graph relationship. Which means you'll also have to modify the `generateCurvePath` utility to not do that.

Here's a gist where I've been playing with this; it's okay for a fairly strict left-to-right and top-to-bottom graph (which is my use case) but you'll need to figure out curve paths that work for your node/link relationships. Hopefully this helps you get started, though: https://gist.github.com/ColemanCollins/541b5987c312e02beb1c10b323db4933

**Comment by Naveenraj006** [comment]
![Screenshot 2020-01-20 at 11 24 23 AM](https://user-images.githubusercontent.com/6183340/72702163-bca07200-3b77-11ea-9903-83facc35f05f.png)

Yes, the curve path differs from the actual start and stop node. So, I wrote a hack with SVG text to display an arrow at the center of the line.

**Comment by Naveenraj006** [comment]
> You can make a custom Link component that uses an SVG `<marker>` to drop an arrowhead on the end of a link. The challenge with this is that the way the current link path drawing/curve generation works, it actually flips the start/end points depending on the spatial relationship of the nodes rather than their directed graph relationship. Which means you'll also have to modify the `generateCurvePath` utility to not do that, because it makes the arrowheads pretty useless.
> 
> Here's a gist where I've been playing with this; it's okay for a fairly strict left-to-right and top-to-bottom graph (which is my use case) but you'll need to figure out curve paths that work for your node/link relationships. Hopefully this is enough to get you moving on your own solution: https://gist.github.com/ColemanCollins/541b5987c312e02beb1c10b323db4933

Thank you coleman.
